name: CICD
on: 
    push: 
        branches: 
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v3
            - name: Loging to DockerHub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build Docker image
              run: docker build -t andryredbee/pokemon-api-back .
            - name: Push Docker image
              run: docker push andryredbee/pokemon-api-back:latest

    deploy:
        needs: build
        runs-on: [aws-ec2]
        steps:
            - name: Pull image from dockerhub
              run: docker pull andryredbee/pokemon-api-back:latest
            - name: Delete old container
              run: docker rm -f pokemon-api-back-container
            - name: Run new container
              run: docker run -d --name pokemon-api-back-container -p 5000:5000 andryredbee/pokemon-api-back:latest
            
